name: CI

on:
  workflow_call:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  required:
    name: Required
    needs: [docs, test]
    runs-on: ubuntu-latest

    steps:
      - name: Status of workflow jobs
        run: echo 'All jobs in this workflow have successfully run'

  docs:
    name: Documentation
    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev

    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      id: setup-beam
      uses: erlef/setup-beam@v1
      with:
        version-file: '.tool-versions'
        version-type: 'strict'
    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: |
          _build
          deps
        key: ${{ runner.os }}-${{ steps.setup-beam.otp-version }}-${{ steps.setup-beam.elixir-version }}-${{ env.MIX_ENV }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ steps.setup-beam.otp-version }}-${{ steps.setup-beam.elixir-version }}-${{ env.MIX_ENV }}-
    - name: Install and compile dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: mix do deps.get --only ${{ env.MIX_ENV }}, deps.compile
    - name: Generate documentation
      run: mix docs --warnings-as-errors

  test:
    name: Tests (Elixir ${{ matrix.elixir }} / OTP ${{ matrix.otp }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        otp: ['24', '25', '26', '27']
        elixir: ['1.15', '1.16', '1.17', '1.18']
        exclude:
          - { elixir: '1.15', otp: '27' }
          - { elixir: '1.16', otp: '27' }
          - { elixir: '1.17', otp: '24' }
          - { elixir: '1.18', otp: '24' }
        include:
          - elixir: '1.18'
            otp: '27'
            lint: true

    env:
      MIX_ENV: test

    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{matrix.elixir}}
        otp-version: ${{matrix.otp}}
    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: |
          _build
          deps
        key: ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-
    - name: Install and compile dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: mix do deps.get, deps.compile
    - name: Check code format
      run: mix format --check-formatted
      if: ${{ matrix.lint }}
    - name: Check for unused dependencies
      run: mix deps.unlock --check-unused
      if: ${{ matrix.lint }}
    - name: Compile code
      run: mix compile
    - name: Run static code analysis
      run: mix credo --strict
      if: ${{ matrix.lint }}
    - name: Run tests
      run: mix test --warnings-as-errors
