name: Publish to Hex.pm

permissions:
  contents: read

on:
  release:
    types: [released]

jobs:
  publish:
    name: Build and publish to hex.pm
    runs-on: ubuntu-22.04
    env:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Setup Elixir
      uses: erlef/setup-beam@v1
      with:
        version-file: '.tool-versions'
        version-type: 'strict'

    - name: Restore dependencies cache
      uses: actions/cache@v5
      with:
        path: deps
        key: ${{ runner.os }}-publish-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-publish-mix-

    - name: Install deps
      run: mix deps.get

    - name: Publish to Hex.pm
      run: mix hex.publish --yes
